const generateWelcomeEmail = (customerName, password) => {
    const emailSubject = 'Welcome to our App!';
    const emailText = `Hello ${customerName}, \n\n Your account has been successfully created. \n\n  Here is your Password: ${password} \n\n Use this password while logging in. \n\n`;
    const emailHtml = `<p>Hello ${customerName},</p><p>Your account has been successfully created.</p><p>Here is your autogenerated password: <strong>${password}</strong></p><p>use this password while login.</p><p>Regards,<br/>The Team</p>`;

    return {
        subject: emailSubject,
        text: emailText,
        html: emailHtml
    };
};

module.exports = {
    generateWelcomeEmail 
};

